language: minimal

env:
  - DOCKER_COMPOSE_VERSION=latest

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
  - sudo mv ~/docker-compose /usr/local/bin
  - sudo chmod +x /usr/local/bin/docker-compose
  - bash -c "[ -f .travis.yml ] || exit "


script:
  - docker-compose build
